### PR TITLE
fix git clone

### PR DESCRIPTION
**Pull request by hobbyquaker**

### CODE REVIEW

**Comment by johndoe31415** [comment]
Hmm. Looking at this wouldn't this give everything in /usr/local the users' permissions?

I'm not sure, but does MacOS have separate users? It's a feature that some operating systems offer. Not sure if it's in their latest revision?

Lrf. Gung jnf n wbxr.

**Comment by hobbyquaker** [comment]
macOS separates privileges in a very sophisticated way. 
```
$ cat /etc/passwd
nobody:*:-2:-2:Unprivileged User:/var/empty:/usr/bin/false
root:*:0:0:System Administrator:/var/root:/bin/sh
hipster:*:31415926535:1337:God Mode:/Users/hipster:/Applications/QuickTime Player.app
```

~~The change just clones to current directory, the `sudo mv` results in `drwxr-xr-x  31 root  wheel   x509sak`~~

yeah. always right u are.

**Comment by johndoe31415** [comment]
Hrhrhr :-P

**Comment by johndoe31415** [comment]
Hmmmm still doesn't work. Shouldn't merge before looking at the code :-)

Users cannot chgrp/chmod in this way. Need at least two more sudos.

**Comment by hobbyquaker** [comment]
yes they can. as you pointed out semi-correctly:
> Looking at this wouldn't this give everything in /usr/local the users' permissions?

-> `this will give /usr/local/x509sak the users' permissions.`

**Comment by johndoe31415** [comment]
Are you sure? On my Linux machine, I get

```
chgrp: changing group of 'x509sak/upd_readme/upd_readme.py': Operation not permitted
chgrp: changing group of 'x509sak/upd_readme/Patcher.py': Operation not permitted
chgrp: changing group of 'x509sak/upd_readme': Operation not permitted
```

When trying to chgrp to "root".

**Comment by hobbyquaker** [comment]
will prove it the hipsters way. With a beautiful very-very-ultra-high-res (!) screenshot:
bildschirmfoto 2018-03-27 um 20 32 36

**Comment by johndoe31415** [comment]
What I'm trying to say is: Shouldn't all /usr/local stuff be chowned, not only chgrped? I.e., root:root under a Linux machine (or whatever the MacOS equivalent is). I.e, the user should not be permitted to modify anything anymore after it's been moved to /usr/local.

**Comment by hobbyquaker** [comment]
Depends. I like it that way because I can just git pull your awesome updates without using sudo. Brew e.g. handles it this way too. You know - single-user-OS, no need to take care of others. They have to buy their own 900g 21sec openssl-build-time macbook-awesomeness 🐣

**Comment by johndoe31415** [comment]
Unforunately I cannot really view the screenshot on my ultra highres 12000 dpi display -- can you maybe post with greater resolution? Screenshots start getting readable on my superior monitor once their size exceeds 10k x 10k pixels, typically. :-D

**Comment by hobbyquaker** [comment]
one moment pls. have to request a "license" for "microsoft office for mac" from my gopnik crew in .ru - then I will embed the 100.000.000px 30bit colordepth .raw in a .docx for you.

**Comment by johndoe31415** [comment]
Hmmmm, I understand the convenience argument but it completely ruins the paranoid-security-aura I'm desperately trying to build up. Effectively it enables one user to make system-wide changes to a command. Don't like it at all. Could you maybe change it so by default that doesn't happen (maybe even additionally to the insecure variant, if there's a warning included)?

Yes, .docx is great. I write all my code in Microsoft Word, so it integrates nicely.

**Comment by hobbyquaker** [comment]
as you wish. #4

**Pull request merged**
